version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: panchtatva-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: panchtatva2024
    networks:
      - panchtatva-network

  redis:
    image: redis:7-alpine
    container_name: panchtatva-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - panchtatva-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: panchtatva-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:panchtatva2024@mongodb:27017/panchtatva-justice?authSource=admin
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/uploads:/app/uploads
    networks:
      - panchtatva-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: panchtatva-web
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./ssl:/etc/nginx/ssl
    networks:
      - panchtatva-network

volumes:
  mongodb_data:
  redis_data:

networks:
  panchtatva-network:
    driver: bridge
